server:
  servlet:
    context-path: /
  port: ${MICROSERVICE_PORT}

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${ROUTE_EUREKA}

spring:
  application:
    name: ${MICROSERVICE_NAME}
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_LOGIN}
    hikari:
      connection-timeout: 5000
  devtools:
    livereload:
      port: ${MICROSERVICE_RELOADPORT}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    properties:
      hibernate:
        '[format_sql]': true
      javax:
        persistence:
          query:
            timeout: 10000
    show-sql: true

springdoc:
 api-docs:
   path: /${MICROSERVICE_NAME}/api-docs 
 swagger-ui:
   path: /${MICROSERVICE_NAME}/swagger-ui.html